// <auto-generated />
namespace HappyZu.CloudStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Trip_Add_Entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Trip_Add_Entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201609220241292_Update_Trip_Add_Entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
